# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

github_packages:
  - assertthat
  - devtools

notifications:
  email:
    on_success: change
    on_failure: change
